import React, { useState, useEffect, useRef, useCallback } from 'react';
import {
    Users, Clock, Search, Maximize, ArrowUpRight, ArrowDownLeft, UserCircle,
    CheckCircle, XCircle, Loader2, Scan, ChevronRight, Camera, CameraOff, X,
    History, FileText, Calendar, Filter, Download, RefreshCw
} from 'lucide-react';
import { Html5QrcodeScanner } from 'html5-qrcode';
import { getTodaysCheckIns, searchMember, checkInMember, checkOutMember, getMemberSuggestions } from '../../api/staff/memberCheckInApi';
import apiClient from '../../api/apiClient';
import toast from 'react-hot-toast';

// ─── PDF Print Helper ────────────────────────────────────────────────────────
const printAttendancePDF = (records, startDate, endDate, branchName = 'Gym') => {
    const rows = records.map((r, i) => `
        <tr style="background:${i % 2 === 0 ? '#fff' : '#f8f9fa'}">
            <td style="padding:10px 14px;border-bottom:1px solid #eee;">${i + 1}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #eee;font-weight:600">${r.name}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #eee;">${r.code}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #eee;">${r.plan}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #eee;">${r.date}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #eee;color:#16a34a">${r.in}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #eee;color:${r.out !== '-' ? '#dc2626' : '#94a3b8'}">${r.out}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #eee;">${r.duration}</td>
            <td style="padding:10px 14px;border-bottom:1px solid #eee;">
                <span style="padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;background:${r.status === 'Inside' ? '#dcfce7' : '#f1f5f9'};color:${r.status === 'Inside' ? '#15803d' : '#64748b'}">${r.status}</span>
            </td>
        </tr>
    `).join('');

    const html = `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8" />
        <title>Attendance Report - ${startDate} to ${endDate}</title>
        <style>
            body { font-family: 'Segoe UI', Arial, sans-serif; margin: 0; color: #1e293b; }
            .header { background: linear-gradient(135deg, #7c3aed, #4f46e5); color: white; padding: 32px 40px; }
            .header h1 { margin: 0 0 4px 0; font-size: 26px; font-weight: 800; letter-spacing: -0.5px; }
            .header p { margin: 0; opacity: 0.8; font-size: 13px; }
            .meta { display: flex; gap: 32px; padding: 20px 40px; background: #f8fafc; border-bottom: 1px solid #e2e8f0; }
            .meta-item { font-size: 12px; color: #64748b; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; }
            .meta-item span { display: block; font-size: 16px; color: #1e293b; font-weight: 800; text-transform: none; margin-top: 2px; }
            table { width: 100%; border-collapse: collapse; }
            thead tr { background:#7c3aed; color:white; }
            thead th { padding: 12px 14px; text-align:left; font-size:11px; font-weight:800; text-transform:uppercase; letter-spacing:0.08em; }
            tbody tr:hover { background: #f1f5f9 !important; }
            .footer { padding: 20px 40px; text-align: center; color: #94a3b8; font-size: 11px; border-top: 1px solid #e2e8f0; margin-top: 20px; }
            @media print { .no-print { display: none; } }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>📋 Attendance Report</h1>
            <p>${branchName} &nbsp;•&nbsp; Generated on ${new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
        </div>
        <div class="meta">
            <div class="meta-item">Date Range <span>${startDate} — ${endDate}</span></div>
            <div class="meta-item">Total Records <span>${records.length}</span></div>
            <div class="meta-item">Currently Inside <span style="color:#16a34a">${records.filter(r => r.status === 'Inside').length}</span></div>
        </div>
        <table>
            <thead>
                <tr>
                    <th>#</th><th>Member Name</th><th>ID</th><th>Plan</th>
                    <th>Date</th><th>Check In</th><th>Check Out</th><th>Duration</th><th>Status</th>
                </tr>
            </thead>
            <tbody>${rows}</tbody>
        </table>
        <div class="footer">This report was generated by Gym Management System &nbsp;•&nbsp; Confidential</div>
    </body>
    </html>`;

    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    win.onload = () => { win.print(); };
};

// ─── Main Component ───────────────────────────────────────────────────────────
const TodaysCheckIns = () => {
    const [activeTab, setActiveTab] = useState('currentlyIn');
    const [searchTerm, setSearchTerm] = useState('');
    const [attendanceData, setAttendanceData] = useState({ currentlyIn: [], history: [], stats: { total: 0, inside: 0, checkedOut: 0 } });
    const [loading, setLoading] = useState(true);
    const [suggestions, setSuggestions] = useState([]);
    const [showSuggestions, setShowSuggestions] = useState(false);
    const [processingId, setProcessingId] = useState(null);
    const [isScanning, setIsScanning] = useState(false);
    const [selectedMember, setSelectedMember] = useState(null);

    // History state
    const [historyRecords, setHistoryRecords] = useState([]);
    const [historyLoading, setHistoryLoading] = useState(false);
    const [historySearch, setHistorySearch] = useState('');
    const [startDate, setStartDate] = useState(() => {
        const d = new Date(); d.setDate(d.getDate() - 7);
        return d.toISOString().split('T')[0];
    });
    const [endDate, setEndDate] = useState(() => new Date().toISOString().split('T')[0]);

    const searchRef = useRef(null);

    // ── Fetch today's data ──────────────────────────────────────────────────
    const fetchData = async () => {
        try {
            const data = await getTodaysCheckIns();
            setAttendanceData(data);
        } catch (error) {
            console.error('Error fetching attendance:', error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchData();
        const interval = setInterval(fetchData, 30000);
        return () => clearInterval(interval);
    }, []);

    // ── Fetch history ───────────────────────────────────────────────────────
    const fetchHistory = useCallback(async () => {
        setHistoryLoading(true);
        try {
            const params = new URLSearchParams({ startDate, endDate });
            if (historySearch) params.append('search', historySearch);
            const res = await apiClient.get(`/staff/attendance/history?${params.toString()}`);
            setHistoryRecords(res.data.records || []);
        } catch (err) {
            toast.error('Failed to load history');
        } finally {
            setHistoryLoading(false);
        }
    }, [startDate, endDate, historySearch]);

    useEffect(() => {
        if (activeTab === 'attendanceHistory') fetchHistory();
    }, [activeTab, fetchHistory]);

    // ── QR Scanner ─────────────────────────────────────────────────────────
    useEffect(() => {
        let sc = null;
        const initScanner = async () => {
            if (isScanning) {
                await new Promise(r => setTimeout(r, 100));
                const element = document.getElementById('reader');
                if (element) {
                    sc = new Html5QrcodeScanner('reader', { fps: 10, qrbox: { width: 250, height: 250 }, aspectRatio: 1.0, showTorchButtonIfSupported: true });
                    sc.render(onScanSuccess, () => { });
                }
            }
        };
        initScanner();
        return () => { if (sc) sc.clear().catch(() => { }); };
    }, [isScanning]);

    const onScanSuccess = (decodedText) => {
        setIsScanning(false);
        setSearchTerm(decodedText);
        handleSearchSubmit(null, decodedText);
    };

    // ── Click outside ───────────────────────────────────────────────────────
    useEffect(() => {
        const handle = (e) => {
            if (searchRef.current && !searchRef.current.contains(e.target)) setShowSuggestions(false);
        };
        document.addEventListener('mousedown', handle);
        return () => document.removeEventListener('mousedown', handle);
    }, []);

    // ── Suggestions ─────────────────────────────────────────────────────────
    useEffect(() => {
        const fetch = async () => {
            if (searchTerm.length >= 2) {
                const results = await getMemberSuggestions(searchTerm);
                setSuggestions(results);
                setShowSuggestions(true);
            } else {
                setSuggestions([]);
                setShowSuggestions(false);
            }
        };
        const t = setTimeout(fetch, 300);
        return () => clearTimeout(t);
    }, [searchTerm]);

    // ── Check In / Out ──────────────────────────────────────────────────────
    const handleCheckIn = async (memberId) => {
        setProcessingId(memberId);
        try {
            const result = await checkInMember(memberId);
            if (result.success) {
                toast.success(result.message || 'Member checked in!');
                fetchData(); setSearchTerm(''); setShowSuggestions(false); setSelectedMember(null);
            } else { toast.error(result.message || 'Check-in failed'); }
        } catch { toast.error('Check-in failed'); } finally { setProcessingId(null); }
    };

    const handleCheckOut = async (memberId) => {
        setProcessingId(memberId);
        try {
            const result = await checkOutMember(memberId);
            if (result.success) { toast.success('Member checked out!'); fetchData(); }
            else { toast.error(result.message || 'Check-out failed'); }
        } catch { toast.error('Check-out failed'); } finally { setProcessingId(null); }
    };

    const handleSearchSubmit = async (e, providedCode) => {
        if (e) e.preventDefault();
        const code = providedCode || searchTerm;
        if (!code) return;
        try {
            const member = await searchMember(code);
            if (member) { setSelectedMember(member); setShowSuggestions(false); }
            else toast.error('No member found');
        } catch { toast.error('Search failed'); }
    };

    const displayList =
        activeTab === 'currentlyIn' ? attendanceData.currentlyIn :
            activeTab === 'absent' ? (attendanceData.absent || []) :
                attendanceData.history;

    // ─────────────────────────────────────────────────────────────────────────
    return (
        <div className="min-h-screen space-y-6 animate-fadeIn">
            {/* Header */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-2xl bg-white shadow-sm border border-slate-100 flex items-center justify-center text-primary">
                        <Scan size={24} />
                    </div>
                    <div>
                        <h1 className="text-3xl font-black text-slate-900 tracking-tight">Attendance</h1>
                        <p className="text-slate-400 font-bold text-xs uppercase tracking-widest mt-0.5">Quick check-in / check-out</p>
                    </div>
                </div>
                <div className="flex items-center gap-3 md:gap-6 bg-white/80 backdrop-blur-md px-6 py-3 rounded-2xl border border-slate-100 shadow-sm">
                    <div className="flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-slate-900" />
                        <span className="text-sm font-bold text-slate-900">{attendanceData.stats.inside} <span className="text-slate-400 font-medium">In</span></span>
                    </div>
                    <div className="h-6 w-px bg-slate-200" />
                    <div className="flex items-center gap-2 text-emerald-600">
                        <ArrowDownLeft size={16} />
                        <span className="text-sm font-bold">{attendanceData.stats.total} <span className="text-slate-400 font-medium ml-1">Today</span></span>
                    </div>
                    <div className="h-6 w-px bg-slate-200" />
                    <div className="flex items-center gap-2 text-rose-500">
                        <ArrowUpRight size={16} />
                        <span className="text-sm font-bold">{attendanceData.stats.checkedOut} <span className="text-slate-400 font-medium ml-1">Out</span></span>
                    </div>
                    <div className="h-6 w-px bg-slate-200" />
                    <div className="flex items-center gap-2 text-slate-400">
                        <XCircle size={16} />
                        <span className="text-sm font-bold">{attendanceData.stats.absent || 0} <span className="text-slate-400 font-medium ml-1">Absent</span></span>
                    </div>
                </div>
            </div>

            {/* Search section — only for today tabs */}
            {activeTab !== 'attendanceHistory' && (
                <div className="flex flex-col gap-4">
                    {isScanning && (
                        <div className="relative bg-slate-900 rounded-[2rem] overflow-hidden shadow-2xl border-4 border-primary/20 max-w-lg mx-auto w-full animate-in zoom-in-95 duration-300">
                            <div id="reader" className="w-full" />
                            <button onClick={() => setIsScanning(false)} className="absolute top-4 right-4 p-2 bg-white/20 hover:bg-white/40 backdrop-blur-md rounded-full text-white transition-all z-50">
                                <X size={20} />
                            </button>
                            <div className="absolute bottom-6 left-0 right-0 text-center z-50">
                                <span className="px-4 py-2 bg-slate-900/80 backdrop-blur-md text-white text-[10px] font-black uppercase tracking-widest rounded-full border border-white/10">
                                    Align Barcode / QR Code within the box
                                </span>
                            </div>
                        </div>
                    )}

                    <div className="relative group w-full" ref={searchRef}>
                        <div className="absolute inset-y-0 left-5 flex items-center pointer-events-none text-slate-300 group-focus-within:text-primary transition-colors">
                            <Search size={22} />
                        </div>
                        <form onSubmit={handleSearchSubmit}>
                            <input
                                type="text"
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                placeholder="Scan barcode or type member code / name / phone..."
                                className="w-full h-16 pl-14 pr-48 rounded-[1.25rem] bg-white border-2 border-slate-100 text-sm font-semibold placeholder:text-slate-300 focus:border-primary focus:ring-8 focus:ring-primary/5 transition-all outline-none shadow-sm"
                                autoFocus
                            />
                            <div className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center gap-2">
                                <button type="button" onClick={() => setIsScanning(!isScanning)}
                                    className={`h-10 px-4 rounded-xl flex items-center gap-2 text-[10px] font-black uppercase tracking-widest transition-all ${isScanning ? 'bg-rose-50 text-rose-600' : 'bg-slate-50 text-slate-600 hover:bg-slate-100'}`}>
                                    {isScanning ? <CameraOff size={14} /> : <Camera size={14} />}
                                    <span className="hidden sm:inline">{isScanning ? 'Stop' : 'Scan'}</span>
                                </button>
                                <button type="submit" className="h-10 px-6 bg-primary text-white rounded-xl text-[10px] font-black uppercase tracking-widest shadow-lg shadow-violet-200 hover:scale-105 active:scale-95 transition-all flex items-center gap-2">
                                    <Search size={14} /> <span className="hidden sm:inline">Search</span>
                                </button>
                            </div>
                        </form>

                        {showSuggestions && suggestions.length > 0 && (
                            <div className="absolute top-full left-0 right-0 mt-3 bg-white border border-slate-100 rounded-2xl shadow-2xl z-50 overflow-hidden animate-in slide-in-from-top-2 duration-200 ring-4 ring-slate-900/5">
                                {suggestions.map((member) => (
                                    <button key={member.id} onClick={() => { setSelectedMember(member); setShowSuggestions(false); }}
                                        disabled={processingId === member.id}
                                        className="w-full px-6 py-4 text-left hover:bg-slate-50 transition-colors flex items-center justify-between group border-b border-slate-50 last:border-0">
                                        <div className="flex items-center gap-4">
                                            <div className="h-10 w-10 rounded-full bg-violet-100 text-primary flex items-center justify-center font-bold text-sm shadow-inner group-hover:scale-110 transition-transform">
                                                {member.name.charAt(0)}
                                            </div>
                                            <div>
                                                <p className="text-sm font-bold text-slate-800">{member.name}</p>
                                                <p className="text-[10px] text-slate-400 font-black uppercase tracking-wider">{member.memberId || member.id} • {member.phone}</p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-3">
                                            <span className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-wide ${member.status === 'Active' ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>
                                                {member.status}
                                            </span>
                                            {processingId === member.id ? <Loader2 size={16} className="animate-spin text-slate-400" /> : <ChevronRight size={16} className="text-slate-300 group-hover:text-primary transition-colors" />}
                                        </div>
                                    </button>
                                ))}
                            </div>
                        )}
                    </div>

                    {selectedMember && (
                        <div className="bg-white rounded-[2rem] p-6 shadow-xl border-2 border-primary/20 animate-in zoom-in-95 duration-300">
                            <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                                <div className="flex items-center gap-6">
                                    <div className="w-20 h-20 rounded-2xl bg-primary/10 flex items-center justify-center text-primary text-3xl font-black">
                                        {selectedMember.name.charAt(0)}
                                    </div>
                                    <div>
                                        <h3 className="text-2xl font-black text-slate-900">{selectedMember.name}</h3>
                                        <div className="flex items-center gap-3 mt-1">
                                            <span className="px-3 py-1 bg-slate-100 rounded-lg text-[10px] font-black uppercase tracking-wider text-slate-500">{selectedMember.memberId || selectedMember.id}</span>
                                            <span className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider ${selectedMember.status === 'Active' ? 'bg-emerald-100 text-emerald-600' : 'bg-rose-100 text-rose-600'}`}>{selectedMember.status}</span>
                                        </div>
                                        <p className="text-sm font-bold text-slate-400 mt-2">{selectedMember.phone}</p>
                                    </div>
                                </div>
                                <div className="flex items-center gap-3 w-full md:w-auto">
                                    <button onClick={() => setSelectedMember(null)} className="flex-1 md:flex-none h-14 px-8 rounded-2xl border-2 border-slate-100 text-slate-400 font-black uppercase tracking-widest text-[10px] hover:bg-slate-50 transition-all">
                                        Cancel
                                    </button>
                                    <button onClick={() => handleCheckIn(selectedMember.id)} disabled={processingId === selectedMember.id}
                                        className="flex-1 md:flex-none h-14 px-10 bg-primary text-white rounded-2xl font-black uppercase tracking-widest text-[10px] shadow-lg shadow-primary/20 hover:scale-105 active:scale-95 transition-all flex items-center justify-center gap-3">
                                        {processingId === selectedMember.id ? <Loader2 size={18} className="animate-spin" /> : <CheckCircle size={18} />}
                                        Check In Now
                                    </button>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            )}

            {/* ── Main Panel ── */}
            <div className="bg-white rounded-[2.5rem] shadow-sm border border-slate-100 overflow-hidden">
                {/* Tabs */}
                <div className="p-2 border-b border-slate-50 flex flex-wrap items-center gap-2 bg-slate-50/50">
                    {[
                        { id: 'currentlyIn', label: `Currently In (${attendanceData.stats.inside})`, icon: Users },
                        { id: 'history', label: `Today's Log (${attendanceData.stats.total})`, icon: Clock },
                        { id: 'absent', label: `Absent (${attendanceData.stats.absent || 0})`, icon: XCircle },
                        { id: 'attendanceHistory', label: 'History & Report', icon: History }
                    ].map(tab => (
                        <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                            className={`px-5 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all flex items-center gap-2 ${activeTab === tab.id ? 'bg-white text-primary shadow-sm border border-slate-100' : 'text-slate-400 hover:text-slate-600'}`}>
                            <tab.icon size={15} /> {tab.label}
                        </button>
                    ))}
                </div>

                {/* ── HISTORY TAB ── */}
                {activeTab === 'attendanceHistory' ? (
                    <div className="p-6 space-y-6">
                        {/* Filters */}
                        <div className="flex flex-col md:flex-row gap-4 items-end">
                            <div className="flex-1 space-y-1">
                                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-1.5"><Calendar size={12} /> Start Date</label>
                                <input type="date" value={startDate} onChange={e => setStartDate(e.target.value)}
                                    className="w-full h-12 px-4 rounded-xl border-2 border-slate-100 bg-white text-sm font-bold text-slate-700 focus:outline-none focus:border-primary transition-all" />
                            </div>
                            <div className="flex-1 space-y-1">
                                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-1.5"><Calendar size={12} /> End Date</label>
                                <input type="date" value={endDate} onChange={e => setEndDate(e.target.value)}
                                    className="w-full h-12 px-4 rounded-xl border-2 border-slate-100 bg-white text-sm font-bold text-slate-700 focus:outline-none focus:border-primary transition-all" />
                            </div>
                            <div className="flex-1 space-y-1">
                                <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-1.5"><Search size={12} /> Search Member</label>
                                <input type="text" placeholder="Name or ID..." value={historySearch} onChange={e => setHistorySearch(e.target.value)}
                                    className="w-full h-12 px-4 rounded-xl border-2 border-slate-100 bg-white text-sm font-bold text-slate-700 focus:outline-none focus:border-primary transition-all" />
                            </div>
                            <div className="flex gap-2 shrink-0">
                                <button onClick={fetchHistory} disabled={historyLoading}
                                    className="h-12 px-6 bg-primary text-white rounded-xl text-[10px] font-black uppercase tracking-widest shadow-lg shadow-violet-100 hover:bg-primary-hover transition-all flex items-center gap-2 disabled:opacity-50">
                                    {historyLoading ? <Loader2 size={14} className="animate-spin" /> : <Filter size={14} />}
                                    Apply
                                </button>
                                <button
                                    onClick={() => historyRecords.length > 0 && printAttendancePDF(historyRecords, startDate, endDate)}
                                    disabled={historyRecords.length === 0}
                                    className="h-12 px-6 bg-slate-900 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-slate-800 transition-all flex items-center gap-2 disabled:opacity-40">
                                    <Download size={14} /> PDF
                                </button>
                            </div>
                        </div>

                        {/* Summary Strip */}
                        {historyRecords.length > 0 && (
                            <div className="flex flex-wrap gap-4 p-5 bg-slate-50 rounded-2xl border border-slate-100">
                                <div className="flex items-center gap-2 text-xs font-black text-slate-500 uppercase tracking-widest">
                                    <FileText size={14} className="text-primary" /> Total: <span className="text-slate-900">{historyRecords.length}</span>
                                </div>
                                <div className="flex items-center gap-2 text-xs font-black text-emerald-600 uppercase tracking-widest">
                                    Currently Inside: <span>{historyRecords.filter(r => r.status === 'Inside').length}</span>
                                </div>
                                <div className="flex items-center gap-2 text-xs font-black text-slate-500 uppercase tracking-widest">
                                    Completed: <span className="text-slate-900">{historyRecords.filter(r => r.status === 'Completed').length}</span>
                                </div>
                            </div>
                        )}

                        {/* Table */}
                        {historyLoading ? (
                            <div className="flex items-center justify-center py-20">
                                <Loader2 className="w-10 h-10 animate-spin text-primary" />
                            </div>
                        ) : historyRecords.length > 0 ? (
                            <div className="overflow-x-auto rounded-2xl border border-slate-100">
                                <table className="w-full text-left">
                                    <thead>
                                        <tr className="bg-slate-50 border-b border-slate-100">
                                            {['Member', 'ID', 'Plan', 'Date', 'Check In', 'Check Out', 'Duration', 'Status'].map(h => (
                                                <th key={h} className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">{h}</th>
                                            ))}
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-50">
                                        {historyRecords.map((r) => (
                                            <tr key={r.id} className="hover:bg-slate-50/50 transition-colors">
                                                <td className="px-6 py-4">
                                                    <div className="flex items-center gap-3">
                                                        <div className="w-9 h-9 rounded-full bg-violet-100 text-primary flex items-center justify-center font-bold text-sm">
                                                            {r.name.charAt(0)}
                                                        </div>
                                                        <span className="text-sm font-bold text-slate-900">{r.name}</span>
                                                    </div>
                                                </td>
                                                <td className="px-6 py-4 text-xs font-bold text-slate-500">{r.code}</td>
                                                <td className="px-6 py-4 text-xs font-bold text-slate-500">{r.plan}</td>
                                                <td className="px-6 py-4 text-xs font-bold text-slate-700">{r.date}</td>
                                                <td className="px-6 py-4 text-xs font-black text-emerald-600">{r.in}</td>
                                                <td className="px-6 py-4 text-xs font-black text-rose-500">{r.out}</td>
                                                <td className="px-6 py-4 text-xs font-bold text-slate-700">{r.duration}</td>
                                                <td className="px-6 py-4">
                                                    <span className={`px-3 py-1 rounded-xl text-[10px] font-black uppercase tracking-widest ${r.status === 'Inside' ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}>
                                                        {r.status}
                                                    </span>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        ) : (
                            <div className="flex flex-col items-center justify-center py-20 text-center">
                                <div className="w-24 h-24 rounded-[3rem] bg-slate-50 flex items-center justify-center text-slate-200 mb-6 border-2 border-dashed border-slate-100">
                                    <History size={48} strokeWidth={1.5} />
                                </div>
                                <h3 className="text-xl font-black text-slate-900 tracking-tight mb-2">No history found</h3>
                                <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Select a date range and click Apply to load records</p>
                            </div>
                        )}
                    </div>
                ) : (
                    /* ── TODAY TABS ── */
                    loading ? (
                        <div className="min-h-[400px] flex items-center justify-center">
                            <Loader2 className="w-10 h-10 animate-spin text-primary" />
                        </div>
                    ) : displayList.length > 0 ? (
                        <div className="overflow-x-auto">
                            <table className="w-full text-left">
                                <thead>
                                    <tr className="border-b border-slate-50 bg-slate-50/30">
                                        <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Member</th>
                                        <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Code</th>
                                        <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Check-in</th>
                                        <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Duration</th>
                                        <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">Action</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-50">
                                    {displayList.map((log) => (
                                        <tr key={log.id} className="hover:bg-slate-50/50 transition-colors group">
                                            <td className="px-8 py-5">
                                                <div className="flex items-center gap-3">
                                                    <div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center text-slate-500 font-bold text-sm">
                                                        {log.name.charAt(0)}
                                                    </div>
                                                    <div>
                                                        <p className="text-sm font-bold text-slate-900 line-clamp-1">{log.name}</p>
                                                        <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">{log.plan}</p>
                                                    </div>
                                                </div>
                                            </td>
                                            <td className="px-8 py-5"><span className="text-xs font-bold text-slate-500">{log.code}</span></td>
                                            <td className="px-8 py-5">
                                                <div className="flex flex-col gap-0.5">
                                                    {log.status === 'Absent' ? (
                                                        <span className="text-xs font-bold text-slate-400 italic">No entry</span>
                                                    ) : (
                                                        <>
                                                            <span className="text-xs font-bold text-slate-900">{log.in}</span>
                                                            {log.out !== '-' && <span className="text-[10px] text-rose-400 font-bold">Out: {log.out}</span>}
                                                        </>
                                                    )}
                                                </div>
                                            </td>
                                            <td className="px-8 py-5"><span className="text-xs font-bold text-slate-900">{log.duration || '-'}</span></td>
                                            <td className="px-8 py-5 text-right">
                                                {log.status === 'Inside' ? (
                                                    <button onClick={() => handleCheckOut(log.memberId)} disabled={processingId === log.memberId}
                                                        className="inline-flex items-center gap-2 px-4 py-2 bg-rose-50 text-rose-600 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-rose-100 active:scale-95 transition-all disabled:opacity-50">
                                                        {processingId === log.memberId ? <Loader2 size={12} className="animate-spin" /> : <XCircle size={14} />}
                                                        Check Out
                                                    </button>
                                                ) : log.status === 'Absent' ? (
                                                    <button onClick={() => handleCheckIn(log.memberId)} disabled={processingId === log.memberId}
                                                        className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-50 text-emerald-600 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-emerald-100 active:scale-95 transition-all disabled:opacity-50">
                                                        {processingId === log.memberId ? <Loader2 size={12} className="animate-spin" /> : <CheckCircle size={14} />}
                                                        Check In
                                                    </button>
                                                ) : (
                                                    <div className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-slate-50 text-slate-400 rounded-lg text-[9px] font-black uppercase tracking-widest">
                                                        <CheckCircle size={12} /> Completed
                                                    </div>
                                                )}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    ) : (
                        <div className="min-h-[400px] flex flex-col items-center justify-center text-center p-20 animate-fadeIn">
                            <div className="relative mb-8">
                                <div className="w-32 h-32 rounded-[3.5rem] bg-gradient-to-br from-slate-50 to-slate-100/50 flex items-center justify-center text-slate-200">
                                    {activeTab === 'currentlyIn' ? <UserCircle size={64} className="text-slate-300" /> : <Clock size={64} className="text-slate-300" />}
                                </div>
                            </div>
                            <h3 className="text-3xl font-black text-slate-900 tracking-tight">
                                {activeTab === 'currentlyIn' ? 'No members currently checked in' : 'No attendance records for today'}
                            </h3>
                            <p className="text-slate-400 text-xs font-bold uppercase tracking-[0.2em] mt-4 max-w-xs leading-relaxed opacity-70">
                                {activeTab === 'currentlyIn' ? 'Scan a barcode or search to record a new check-in' : 'Attendance logs will appear here once members start checking in'}
                            </p>
                            <div className="mt-10 flex items-center gap-2 px-4 py-2 bg-emerald-50 rounded-full border border-emerald-100">
                                <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                                <span className="text-[10px] font-black text-emerald-600 uppercase tracking-widest">System Online</span>
                            </div>
                        </div>
                    )
                )}
            </div>
        </div>
    );
};

export default TodaysCheckIns;
